#requires -Version 7
# Build the images with your PRODUCTION domain baked in, save them to ONE tar file, and
# stage the unraid/ deploy folder (config + .env). Then you copy just unraid/ to the NAS.
#
#   pwsh -File scripts/build_for_unraid.ps1                       # uses default domain
#   pwsh -File scripts/build_for_unraid.ps1 -Domain chat.x.org   # override domain
#
# The domain is COMPILED into the SPA, so this is domain-specific. Re-run if it changes.

param(
	[string]$Domain = 'fluxer.bigweld.duckdns.org',
	[string]$Scheme = 'https',
	[int]$Port = 443
)
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
Set-Location $root

function Invoke-Step($desc, [scriptblock]$block) {
	Write-Host "==> $desc" -ForegroundColor Cyan
	& $block
	if ($LASTEXITCODE -ne 0) { Write-Host "FAILED: $desc (exit $LASTEXITCODE)" -ForegroundColor Red; exit $LASTEXITCODE }
}

# Bake the production domain into the build (overrides .env for this process only).
$env:BASE_DOMAIN   = $Domain
$env:PUBLIC_SCHEME = $Scheme
$env:PUBLIC_PORT   = "$Port"
$files = @('-f', 'compose.yaml', '-f', 'compose.localhost.yaml')

Invoke-Step "Seeding production config for $Domain (secrets + voice keys + livekit.yaml)" {
	# Generate config/config.json from the duckdns template if missing; --force re-renders
	# livekit.yaml. Existing real secrets are preserved (only placeholders are filled).
	node scripts/seed_config.mjs config/config.json --from config/config.duckdns.template.json
}

# If config.json was seeded earlier for a DIFFERENT domain, fix the domain fields in place
# (without disturbing secrets), so the runtime config matches the baked-in SPA domain.
Invoke-Step "Aligning config/config.json domain to $Domain" {
	node -e "const f='config/config.json',c=JSON.parse(require('fs').readFileSync(f));c.domain.base_domain='$Domain';c.domain.public_scheme='$Scheme';c.domain.public_port=$Port;c.s3.endpoint='$Scheme'+'://'+'$Domain'+'/s3';if(c.integrations?.voice)c.integrations.voice.url=('$Scheme'==='https'?'wss':'ws')+'://'+'$Domain'+'/livekit';require('fs').writeFileSync(f,JSON.stringify(c,null,'\t')+'\n');console.log('domain ->','$Domain')"
}

Invoke-Step 'Building images (domain baked in — Rust/WASM + Erlang + SPA)' {
	docker compose @files build fluxer_gateway fluxer_server
}

Invoke-Step 'Saving images to unraid/fluxer-images.tar (one file)' {
	docker save fluxer-server:local fluxer-gateway:local -o unraid/fluxer-images.tar
}

# Stage config into unraid/config/
New-Item -ItemType Directory -Force unraid/config | Out-Null
Copy-Item config/config.json  unraid/config/ -Force
Copy-Item config/Caddyfile    unraid/config/ -Force
if (Test-Path config/livekit.yaml) { Copy-Item config/livekit.yaml unraid/config/ -Force }

# Stage unraid/.env (carry the SMTP password from the root .env if present).
$smtp = ''
if (Test-Path .env) {
	$line = Select-String -Path .env -Pattern '^\s*FLUXER_SMTP_PASSWORD\s*=' | Select-Object -First 1
	if ($line) { $smtp = ($line.Line -replace '^\s*FLUXER_SMTP_PASSWORD\s*=', '').Trim() }
}
@"
# Unraid deploy env — generated by build_for_unraid.ps1. Gitignored (holds the SMTP secret).
FLUXER_SERVER_IMAGE=fluxer-server:local
FLUXER_GATEWAY_IMAGE=fluxer-gateway:local
FLUXER_SMTP_PASSWORD=$smtp
"@ | Set-Content unraid/.env

$tar = (Get-Item unraid/fluxer-images.tar).Length / 1GB
Write-Host ''
Write-Host ("Done. unraid/ is staged (image tar = {0:N2} GB)." -f $tar) -ForegroundColor Green
Write-Host 'Copy the whole unraid/ folder to your NAS, then on Unraid:' -ForegroundColor Green
Write-Host '  docker load -i fluxer-images.tar'        -ForegroundColor Gray
Write-Host '  docker network create bignet   # if needed' -ForegroundColor Gray
Write-Host '  docker compose --profile voice up -d'    -ForegroundColor Gray
