#requires -Version 7
# Build images with your PRODUCTION domain baked in, then push them to your private
# registry on Unraid. After this, the NAS just runs `docker compose pull && up -d`.
#
#   pwsh -File scripts/build_and_push.ps1 -Registry 192.168.1.50:5000
#   pwsh -File scripts/build_and_push.ps1 -Registry 192.168.1.50:5000 -Domain chat.x.org
#
# ONE-TIME on the Windows dev box: add the registry to Docker Desktop's insecure list
# (Settings -> Docker Engine), then Apply & Restart:
#     "insecure-registries": ["192.168.1.200:5024"]
# (LAN HTTP. For HTTPS instead, put the registry behind NPM with a cert — see README.)

param(
	[Parameter(Mandatory)][string]$Registry,   # <unraid-ip>:<port>, e.g. 192.168.1.200:5024
	[string]$Domain = 'fluxer.bigweld.duckdns.org',
	[string]$Scheme = 'https',
	[int]$Port = 443,
	[string]$Tag = 'latest'
)
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
Set-Location $root

function Invoke-Step($desc, [scriptblock]$block) {
	Write-Host "==> $desc" -ForegroundColor Cyan
	& $block
	if ($LASTEXITCODE -ne 0) { Write-Host "FAILED: $desc (exit $LASTEXITCODE)" -ForegroundColor Red; exit $LASTEXITCODE }
}

$env:BASE_DOMAIN = $Domain; $env:PUBLIC_SCHEME = $Scheme; $env:PUBLIC_PORT = "$Port"
$files = @('-f', 'compose.yaml', '-f', 'compose.localhost.yaml')

Invoke-Step "Seeding production config for $Domain" {
	node scripts/seed_config.mjs config/config.json --from config/config.duckdns.template.json
}
Invoke-Step "Aligning config/config.json domain to $Domain" {
	node -e "const f='config/config.json',c=JSON.parse(require('fs').readFileSync(f));c.domain.base_domain='$Domain';c.domain.public_scheme='$Scheme';c.domain.public_port=$Port;c.s3.endpoint='$Scheme'+'://'+'$Domain'+'/s3';if(c.integrations?.voice)c.integrations.voice.url=('$Scheme'==='https'?'wss':'ws')+'://'+'$Domain'+'/livekit';require('fs').writeFileSync(f,JSON.stringify(c,null,'\t')+'\n')"
}
Invoke-Step 'Building images (domain baked in)' {
	docker compose @files build fluxer_gateway fluxer_server
}

$srv = "$Registry/fluxer-server:$Tag"
$gw = "$Registry/fluxer-gateway:$Tag"
Invoke-Step "Tagging + pushing to $Registry" {
	docker tag fluxer-server:local  $srv
	docker tag fluxer-gateway:local $gw
	docker push $srv
	docker push $gw
}

# Stage the deploy folder (config + .env) — NO tar needed; images live in the registry.
New-Item -ItemType Directory -Force unraid/config | Out-Null
Copy-Item config/config.json unraid/config/ -Force
Copy-Item config/Caddyfile   unraid/config/ -Force
if (Test-Path config/livekit.yaml) { Copy-Item config/livekit.yaml unraid/config/ -Force }

$smtp = ''
if (Test-Path .env) {
	$line = Select-String -Path .env -Pattern '^\s*FLUXER_SMTP_PASSWORD\s*=' | Select-Object -First 1
	if ($line) { $smtp = ($line.Line -replace '^\s*FLUXER_SMTP_PASSWORD\s*=', '').Trim() }
}
# On the NAS, pull from localhost:<port> (the registry runs there) — Docker treats
# localhost registries as insecure-OK automatically, so no daemon.json change needed there.
# Derive the port from the -Registry you pushed to (e.g. 192.168.1.200:5024 -> 5024).
$regPort = if ($Registry -match ':(\d+)$') { $Matches[1] } else { '5000' }
@"
# Unraid deploy env — generated by build_and_push.ps1. Gitignored (holds the SMTP secret).
FLUXER_SERVER_IMAGE=localhost:$regPort/fluxer-server:$Tag
FLUXER_GATEWAY_IMAGE=localhost:$regPort/fluxer-gateway:$Tag
FLUXER_SMTP_PASSWORD=$smtp
# Absolute path to the unraid/ folder ON THE NAS — Compose Manager needs this to find config/.
# Edit if you put the stack somewhere else.
FLUXER_APPDATA=/mnt/user/nvme_array/appdata/Fluxer/unraid
# NSFW image scanning OFF (slim image has no ONNX model). Set to false to re-enable
# (requires the model baked in via INCLUDE_NSFW_ML=true at build time).
FLUXER_DISABLE_NSFW=true
"@ | Set-Content unraid/.env

Write-Host ''
Write-Host "Pushed $srv and $gw" -ForegroundColor Green
Write-Host 'Copy unraid/ (compose.yaml + config/ + .env) to the NAS, then on Unraid:' -ForegroundColor Green
Write-Host '  docker compose pull'                  -ForegroundColor Gray
Write-Host '  docker compose --profile voice up -d' -ForegroundColor Gray
Write-Host 'Subsequent updates: re-run this script, then `docker compose pull && up -d` on the NAS (only changed layers transfer).' -ForegroundColor DarkGray
